
services:
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=auth
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://serverecommerce.database.windows.net:1433;database=ecommerce;user=angel@serverecommerce;password=141198Ss;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - SPRING_DATASOURCE_USERNAME=angel
      - SPRING_DATASOURCE_PASSWORD=141198Ss
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServerDialect
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_INSTANCE_HOSTNAME=auth-service
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - network

networks:
  network:
    driver: bridge
