"""Create a baseline migrations

Revision ID: 23cf0c5ace0c
Revises: 
Create Date: 2024-02-07 01:00:47.004238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cf0c5ace0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=50), nullable=False),
    sa.Column('carrera', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('indicador', sa.String(length=50), nullable=False),
    sa.Column('diagonal', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_de_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagen_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagen_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paypal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_de_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.Integer(), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('tipo_de_documento_id', sa.Integer(), nullable=False),
    sa.Column('url_imagen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_de_documento_id'], ['tipo_de_documento.id'], ),
    sa.ForeignKeyConstraint(['url_imagen_id'], ['imagen_usuario.id'], ),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.Integer(), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('grupo_rol_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruporol_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruporol_id'], ['grupo_de_permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupopermisos_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupopermisos_id', sa.Integer(), nullable=False),
    sa.Column('permisos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupopermisos_id'], ['grupo_de_permisos.id'], ),
    sa.ForeignKeyConstraint(['permisos_id'], ['permisos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_transaccion', sa.Date(), nullable=False),
    sa.Column('paypal_id', sa.Integer(), nullable=True),
    sa.Column('tarjetas_id', sa.Integer(), nullable=True),
    sa.Column('estado_pago_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['estado_pago_id'], ['estado_pago.id'], ),
    sa.ForeignKeyConstraint(['paypal_id'], ['paypal.id'], ),
    sa.ForeignKeyConstraint(['tarjetas_id'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('grupo_rol_permisos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['grupo_rol_permisos_id'], ['grupo_rol_permisos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('det_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['detalle_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('det_pedido')
    op.drop_table('usuarios')
    op.drop_table('pais')
    op.drop_table('metodos_pago')
    op.drop_table('detalle_producto')
    op.drop_table('productos')
    op.drop_table('grupopermisos_permisos')
    op.drop_table('grupo_rol_permisos')
    op.drop_table('factura')
    op.drop_table('departamentos')
    op.drop_table('clientes')
    op.drop_table('tipo_de_documento')
    op.drop_table('tarjetas')
    op.drop_table('rol')
    op.drop_table('permisos')
    op.drop_table('pedido')
    op.drop_table('paypal')
    op.drop_table('municipios')
    op.drop_table('imagen_usuario')
    op.drop_table('imagen_producto')
    op.drop_table('grupo_de_permisos')
    op.drop_table('estado_pago')
    op.drop_table('direccion')
    op.drop_table('ciudades')
    op.drop_table('categoria')
    # ### end Alembic commands ###
