# Usa la imagen base de Nginx
FROM nginx

# Copia el archivo de configuración de Nginx al contenedor
COPY api_gateway.conf /etc/nginx/conf.d/api_gateway.conf

# Expone el puerto 80 para las solicitudes HTTP
EXPOSE 80

# Comando para iniciar Nginx cuando se inicie el contenedor
CMD ["nginx", "-g", "daemon off;"]