name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t my-auth-service ./auth

      - name: Push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          docker tag my-auth-service angkash/my-auth-service:latest
          docker push angkash/my-auth-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
